---
server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moany-api
    username: moany-api
    password: P@ssW0rd
#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: none
